[project]
name = "text-app-backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "alembic>=1.19.1",
    "dotenv>=0.9.9",
    "fastapi>=0.141.1",
    "psycopg2>=2.9.12",
    "sqlalchemy>=2.0.52",
    "uvicorn>=0.52.4",
]
